baseurl: https://blog.tekzv.com
languageCode: zh-cn
theme: stack
paginate: 5
title: TeKzV 闲聊小屋

# Change it to your Disqus shortname before using
disqusShortname: tekzvs-blog

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: zh-cn

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - posts
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🍥
        subtitle: wubba lubba dub dub.
        avatar:
            local: false
            src: https://tekzv-blog.oss-cn-chengdu.aliyuncs.com/FNg5uK.jpeg?x-oss-process=style/webp

    article:
        math: false
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus
        utterances:
            repo: tinyratp/blog
            issueTerm: pathname
            label: comment
            theme: preferred-color-scheme

    widgets:
        enabled:
            # - search
            # - archives
            - tag-cloud

        archives:
            limit: 5
            path: archives

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site: qMgzIx

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home

        - identifier: about
          name: About
          url: about
          weight: -90
          pre: user

        # - identifier: archives
          # name: Archives
          # url: archives
          # weight: -70
          # pre: archives

        # - identifier: search
          # name: Search
          # url: search
          # weight: -60
          # pre: search

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false
